DROP TABLE IF EXISTS magasin Cascade ;
DROP TABLE IF EXISTS produit Cascade;
DROP TABLE IF EXISTS client Cascade;
DROP TABLE IF EXISTS cataloge Cascade;
DROP TABLE IF EXISTS reduit_imme Cascade;
DROP TABLE IF EXISTS bon_achat Cascade;
DROP TABLE IF EXISTS achat_facture Cascade;
DROP TABLE IF EXISTS categorie Cascade;
DROP TABLE IF EXISTS cartefiedlite Cascade;
DROP TABLE IF EXISTS cartepayement Cascade;
DROP TABLE IF EXISTS produit_magasin Cascade;
DROP TABLE IF EXISTS achat_produit Cascade;
DROP TABLE IF EXISTS cataloge_produit Cascade;
DROP TABLE IF EXISTS dates Cascade;
CREATE TABLE magasin (id_magasin  SERIAL NOT NULL, address_magasin text NOT NULL, PRIMARY KEY (id_magasin));
CREATE TABLE produit (id_produit  SERIAL NOT NULL, nom_produit text NOT NULL, prix_achat float4 NOT NULL, reference_local int4 NOT NULL, date_peremption date NOT NULL, id_categorie int4 NOT NULL, quantite_limitee int4 NOT NULL, PRIMARY KEY (id_produit));
CREATE TABLE client (id_client  SERIAL NOT NULL, nom_client text NOT NULL, prenom_client text NOT NULL, PRIMARY KEY (id_client));
CREATE TABLE cataloge (id_cataloge  SERIAL NOT NULL, date_debut date NOT NULL, date_fin date NOT NULL, id_reduit_imme int4 NOT NULL, id_bon_achat int4 NOT NULL, PRIMARY KEY (id_cataloge), CONSTRAINT da CHECK (date_fin-date_debut=6));
CREATE TABLE reduit_imme (id_reduit_imme  SERIAL NOT NULL, montant_reduit float4 DEFAULT 0 NOT NULL, pourcentage float4 DEFAULT 0 NOT NULL CHECK(pourcentage<=1), PRIMARY KEY (id_reduit_imme), CONSTRAINT q CHECK (montant_reduit=0 OR pourcentage=0));
CREATE TABLE bon_achat (id_bon_achat  SERIAL NOT NULL, montant_calcul float4 DEFAULT 0 NOT NULL, PRIMARY KEY (id_bon_achat));
CREATE TABLE achat_facture (id_achat  SERIAL NOT NULL, id_client int4 NOT NULL, date_achat date NOT NULL, prix_total float4 DEFAULT 0 NOT NULL, montant_payer float4 DEFAULT 0 NOT NULL, PRIMARY KEY (id_achat));
CREATE TABLE categorie (id_categorie  SERIAL NOT NULL, nom_categorie text NOT NULL, id_souscategorie int4 NOT NULL, PRIMARY KEY (id_categorie));
CREATE TABLE cartefiedlite (id_client int4 NOT NULL CHECK(id_client!=0 AND id_client%2=0), point int4 DEFAULT 0 NOT NULL, PRIMARY KEY (id_client));
CREATE TABLE cartepayement (id_client int4 NOT NULL CHECK(id_client%2=1), credit_calcule float4 DEFAULT 0 NOT NULL, taux_credit float4 DEFAULT 0 NOT NULL, PRIMARY KEY (id_client));
CREATE TABLE produit_magasin (id_produit int4 NOT NULL, id_magasin int4 NOT NULL, prix_vente float4 NOT NULL, quantite_stock int4 DEFAULT 0 NOT NULL, PRIMARY KEY (id_produit, id_magasin));
CREATE TABLE achat_produit (id_achat int4 NOT NULL, id_magasin int4 NOT NULL, id_produit int4 NOT NULL, quantite_achat int4 DEFAULT 0 NOT NULL, prix_achat_client float4 DEFAULT 0 NOT NULL, PRIMARY KEY (id_achat, id_magasin, id_produit));
CREATE TABLE cataloge_produit (id_cataloge int4 NOT NULL, id_produit int4 NOT NULL, PRIMARY KEY (id_cataloge, id_produit));
CREATE TABLE dates (dates date NOT NULL, PRIMARY KEY (dates));
ALTER TABLE achat_facture ADD CONSTRAINT FKachat_fact88795 FOREIGN KEY (id_client) REFERENCES client (id_client) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE produit ADD CONSTRAINT FKproduit189338 FOREIGN KEY (id_categorie) REFERENCES categorie (id_categorie) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE cartefiedlite ADD CONSTRAINT FKcartefiedl978185 FOREIGN KEY (id_client) REFERENCES client (id_client) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE produit_magasin ADD CONSTRAINT FKproduit_ma616008 FOREIGN KEY (id_produit) REFERENCES produit (id_produit) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE produit_magasin ADD CONSTRAINT FKproduit_ma231057 FOREIGN KEY (id_magasin) REFERENCES magasin (id_magasin) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE cataloge ADD CONSTRAINT FKcataloge951419 FOREIGN KEY (id_reduit_imme) REFERENCES reduit_imme (id_reduit_imme) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE cataloge ADD CONSTRAINT FKcataloge980142 FOREIGN KEY (id_bon_achat) REFERENCES bon_achat (id_bon_achat) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE cartepayement ADD CONSTRAINT FKcartepayem695752 FOREIGN KEY (id_client) REFERENCES client (id_client) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE cataloge_produit ADD CONSTRAINT FKcataloge_p421674 FOREIGN KEY (id_produit) REFERENCES produit (id_produit) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE cataloge_produit ADD CONSTRAINT FKcataloge_p437957 FOREIGN KEY (id_cataloge) REFERENCES cataloge (id_cataloge) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE categorie ADD CONSTRAINT FKcategorie728468 FOREIGN KEY (id_souscategorie) REFERENCES categorie (id_categorie) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE achat_produit ADD CONSTRAINT FKachat_prod287309 FOREIGN KEY (id_achat) REFERENCES achat_facture (id_achat) ON UPDATE Cascade ON DELETE Cascade;
ALTER TABLE achat_produit ADD CONSTRAINT FKachat_prod263961 FOREIGN KEY (id_produit, id_magasin) REFERENCES produit_magasin (id_produit, id_magasin) ON UPDATE Cascade ON DELETE Cascade;
